version: "3"

services:
  grpc_server:
    build: .
    container_name: grpc_server
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    command: [ "sh", "./scripts/start.sh" ]

  envoy:
    image: envoyproxy/envoy:v1.24-latest
    container_name: envoy
    ports:
      - "8080:8080"
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
      - ./proto/hello.pb:/etc/envoy/hello.pb

networks:
  backend:
    driver: bridge
