version: "3.9"

services:
  web:
    build: .
    container_name: django_grpc_web
    ports:
      - "8000:8000"  
      - "50051:50051"
    volumes:
      - .:/app
    command: grpc_server.py  

    networks:
      - backend
    environment:
      - PYTHONPATH=/app

networks:
  backend:
    driver: bridge
